# -*- coding: utf-8 -*-
"""class_roster.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k_2UkIYlYRuyeJQEMyTy9-SCtsrJ52GH
"""

print("===== CLASS ROSTER BUILDER =====")
print()

print("STUDENT 1:")
student1_name = input("Enter name: ")
student1_age = input("Enter age: ")
student1_major = input("Enter major: ")
print()

print("STUDENT 2:")
student2_name = input("Enter name: ")
student2_age = input("Enter age: ")
student2_major = input("Enter major: ")
print()

print("STUDENT 3:")
student3_name = input("Enter name: ")
student3_age = input("Enter age: ")
student3_major = input("Enter major: ")
print()

print("===== CLASS ROSTER =====")
print()
print("Student 1:",student1_name + ", Age: " +student1_age+", Major: "+student1_major)
print("Student 2:",student2_name + ", Age: " +student2_age+", Major: "+student2_major)
print("Student 3:",student3_name + ", Age: " +student3_age+", Major: "+student3_major)

print()
print("Total Students: ",3)
print("======================")