# -*- coding: utf-8 -*-
"""student_intro.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0LWAZA12on7psL4_xa1W92xiRFhaamC
"""

name = input("Enter your name: ")
subject = input("Enter your favorite subject: ")
print("Hello "+name+"!")
print("Your favorite subject is "+ subject+". That's intresting!")